### ISSUE TITLE
Update eslint dep to v8

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/eslint-config-standard#10]
Could we update the eslint dep to either v8 or v7 | v8?
npm errors over this when eslint 8 is being used as the peer dep is tied to v7

**Comment by josephzidell** [comment]
Any progress on this?

**Comment by Tofandel** [comment]
Yep, it works normally with eslint 8 if force upgrade so it would be nice to upgrade it

**Comment by MatthijsBurgh** [comment]
@sodatea would it be possible to allow eslint 8?

**Comment by dakshshah96** [comment]
Can someone from the Vue team please take a look at this? A huge blocker for upgrading to ESLint 8, and this package has 147,169 weekly downloads on npm.

cc @yyx990803 @sodatea

**Comment by sodatea** [comment]
Please be patient. Neither has the upstream `eslint-config-standard` package shipped an ESLint-8-compatible stable version https://github.com/standard/eslint-config-standard/issues/208

I wish I can ship a new version ASAP too.
But my time and energy are limited. This doesn't have to be a high-priority issue, at least for now.

**Comment by Tofandel** [comment]
@sodatea eslint-config-standard 17 just got released, so the door is now open for eslint 8

**Comment by MatthijsBurgh** [comment]
@sodatea @yyx990803 Friendly ping ;)

**Comment by sodatea** [comment]
https://github.com/vuejs/eslint-config-standard/releases/tag/v7.0.0

**Comment by Tofandel** [comment]
Thank you so much @sodatea

**Comment by dakshshah96** [comment]
Thanks a lot, @sodatea!
