### ISSUE TITLE
Error installing eslint-plugin-promise 6.0.0

### ISSUE THREAD

**Issue by mdellanave** [vuejs/eslint-config-standard#13]
While resolving: eslint-config-standard@16.0.3
Found: eslint-plugin-promise@6.0.0
node_modules/eslint-plugin-promise
  dev eslint-plugin-promise@"^6.0.0" from the root project

Could not resolve dependency:
peer eslint-plugin-promise@"^4.2.1 || ^5.0.0" from eslint-config-standard@16.0.3
node_modules/eslint-config-standard
  dev eslint-config-standard@"^16.0.3" from the root project

Conflicting peer dependency: eslint-plugin-promise@5.2.0
node_modules/eslint-plugin-promise
  peer eslint-plugin-promise@"^4.2.1 || ^5.0.0" from eslint-config-standard@16.0.3
  node_modules/eslint-config-standard
    dev eslint-config-standard@"^16.0.3" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

**Comment by sodatea** [comment]
Fixed in the latest version
