### ISSUE TITLE
eslint-config-standard peer conflict when use eslint-plugin-vue@8

### ISSUE THREAD

**Issue by hankaibo** [vuejs/eslint-config-standard#14]
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2022-03-24T08_57_37_606Z-debug.log
PS F:\project\thtf-template> npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: thtf-template@0.0.1
npm ERR! Found: eslint-plugin-vue@8.5.0
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   dev eslint-plugin-vue@"^8.5.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-vue@"^7.0.0" from @vue/eslint-config-standard@6.1.0
npm ERR! node_modules/@vue/eslint-config-standard
npm ERR!   dev @vue/eslint-config-standard@"^6.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by glutaminefree** [comment]
Same problem

**Comment by kgeorgy** [comment]
Same problem, anybody to just fix this dependency issue?

**Comment by glutaminefree** [comment]
```
npm install --legacy-peer-deps
```
as temporary solution

**Comment by sodatea** [comment]
https://github.com/vuejs/eslint-config-standard/releases/tag/v7.0.0
