### ISSUE TITLE
Conflicting with ESLint 8.16

### ISSUE THREAD

**Issue by MartinX3** [vuejs/eslint-config-standard#20]
Is there are reason ESLint `8.0.1` is enforced?
It's 8 months old, but the release enforcing it came 20 days ago when ESLint `8.15.0` was the current version.

`Standard` also wants ESLint `8.13.0`.

And please update it to eslint-plugin-vue `9.1.0`.

**Comment by sodatea** [comment]
Fixed in the latest version
