### ISSUE TITLE
Error: Cannot find module '@vue/cli-service/webpack.config.js'

### ISSUE THREAD

**Issue by hawkeye64** [vuejs/eslint-config-standard#3]
**What version of this package are you using?**
v5.1.1

**What operating system, Node.js, and npm version?**
Ubuntu v18.04
Node v12.16.0
Yarn 1.21.1

**What happened?**
Updated packages and get the following when eslint is run:
```
Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):
Cannot read config file: /home/intelliview/git/projects/NewCode/System_Console/projects/web/src/client/node_modules/@vue/eslint-config-standard/index.js
Error: Cannot find module '@vue/cli-service/webpack.config.js'
Require stack:
- /home/intelliview/git/projects/NewCode/System_Console/projects/web/src/client/node_modules/@vue/eslint-config-standard/index.js
- /home/intelliview/git/projects/NewCode/System_Console/projects/web/src/client/node_modules/eslint/lib/cli-engine/config-array-factory.js
- /home/intelliview/git/projects/NewCode/System_Console/projects/web/src/client/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js
- /home/intelliview/git/projects/NewCode/System_Console/projects/web/src/client/node_modules/eslint/lib/cli-engine/cli-engine.js
- /home/intelliview/git/projects/NewCode/System_Console/projects/web/src/client/node_modules/eslint/lib/cli-engine/index.js
- /home/intelliview/git/projects/NewCode/System_Console/projects/web/src/client/node_modules/eslint/lib/api.js
```

**What did you expect to happen?**
No issues for lack of finding a config file. It appears to be looking for `'@vue/cli-service/webpack.config.js'`. Was this always the case or a breaking change?? We are trying to get a build done at work and now cannot.

We tried installing:
```
yarn add -D @vue/cli-service
```
As much as we'd like Vue eslinting, it appears we'll be forced to remove.

I believe this line:
https://github.com/vuejs/eslint-config-standard/commit/f78b634fc8c5526cb9d01b4861e1f52c560257d2#diff-168726dbe96b3ce427e7fedce31bb0bcR10

Assumes that all Vue projects are using the Vue CLI. I believe you have broken all the Quasar Framework projects out there.

**Comment by sodatea** [comment]
Fixed 5.1.2

**Comment by hawkeye64** [comment]
Thanks @sodatea ! Quite unexpected. I do appreciate it.

**Comment by calebadeleye** [comment]
I am having this error too, it all stared when i created a project in Vue3
